package com.example.ui.components

object Localization {
    private val translations = mapOf(
        "English" to mapOf(
            "wizard_title" to "Merchant Onboarding",
            "wizard_subtitle" to "Configure your APMC Mandi business in 5 quick steps",
            "step_1_title" to "General Info",
            "step_2_title" to "Legal Details",
            "step_3_title" to "Payments",
            "step_4_title" to "Preferences",
            "step_5_title" to "Review & Sync",
            "shop_name" to "Shop / Firm Name",
            "owner_name" to "Merchant Owner Name",
            "gst_number" to "GSTIN (GST Number)",
            "apmc_license" to "APMC License Number",
            "address" to "Market Yard Address",
            "invoice_prefix" to "Bill Invoice Prefix",
            "upi_id" to "UPI Address (VPA)",
            "bank_name" to "Bank Name",
            "bank_acc_name" to "Account Holder Name",
            "bank_acc_num" to "Account Number",
            "bank_ifsc" to "IFSC Code",
            "printer_settings" to "Printer Setup",
            "theme" to "System Theme",
            "language" to "System Language",
            "save_changes" to "Save & Continue",
            "finish_setup" to "Complete Wizard",
            "back" to "Previous",
            "skip" to "Skip Setup",
            "preset_logo" to "Select Business Icon",
            "print_auto" to "Print Invoice Automatically on Save",
            "syncing" to "Uploading configurations to Supabase Cloud...",
            "sync_done" to "All settings are securely stored and synced!",
            "logo_label" to "Upload Logo / Select Branding"
        ),
        "Hindi" to mapOf(
            "wizard_title" to "व्यापारी ऑनबोर्डिंग",
            "wizard_subtitle" to "5 त्वरित चरणों में अपने एपीएमसी मंडी व्यवसाय को कॉन्फ़िगर करें",
            "step_1_title" to "सामान्य जानकारी",
            "step_2_title" to "कानूनी विवरण",
            "step_3_title" to "भुगतान विवरण",
            "step_4_title" to "प्राथमिकताएं",
            "step_5_title" to "समीक्षा और सिंक",
            "shop_name" to "दुकान / फर्म का नाम",
            "owner_name" to "व्यापारी मालिक का नाम",
            "gst_number" to "जीएसटी नंबर (GSTIN)",
            "apmc_license" to "एपीएमसी लाइसेंस संख्या",
            "address" to "मार्केट यार्ड का पता",
            "invoice_prefix" to "बिल चालान उपसर्ग (Prefix)",
            "upi_id" to "यूपीआई आईडी (VPA)",
            "bank_name" to "बैंक का नाम",
            "bank_acc_name" to "खाताधारक का नाम",
            "bank_acc_num" to "खाता संख्या",
            "bank_ifsc" to "आईएफएससी (IFSC) कोड",
            "printer_settings" to "प्रिंटर सेटअप",
            "theme" to "सिस्टम थीम",
            "language" to "सिस्टम भाषा",
            "save_changes" to "सहेजें और जारी रखें",
            "finish_setup" to "सेटअप पूरा करें",
            "back" to "पीछे",
            "skip" to "छोड़ें",
            "preset_logo" to "व्यवसाय आइकन चुनें",
            "print_auto" to "सहेजने पर स्वचालित रूप से बिल प्रिंट करें",
            "syncing" to "सुपाबेस क्लाउड पर कॉन्फ़िगरेशन अपलोड किया जा रहा है...",
            "sync_done" to "सभी सेटिंग्स सुरक्षित रूप से संग्रहीत और सिंक हो गई हैं!",
            "logo_label" to "लोगो अपलोड करें / ब्रांडिंग चुनें"
        ),
        "Marathi" to mapOf(
            "wizard_title" to "व्यापारी ऑनबोर्डिंग",
            "wizard_subtitle" to "५ सोप्या टप्प्यांत आपल्या एपीएमसी मंडी व्यवसायाची रचना करा",
            "step_1_title" to "सामान्य माहिती",
            "step_2_title" to "कायदेशीर तपशील",
            "step_3_title" to "पेमेंट तपशील",
            "step_4_title" to "प्राधान्ये",
            "step_5_title" to "पुनरावलोकन आणि सिंक",
            "shop_name" to "दुकान / पेढीचे नाव",
            "owner_name" to "मालकाचे नाव",
            "gst_number" to "जीएसटी क्रमांक (GSTIN)",
            "apmc_license" to "एपीएमसी परवाना क्रमांक",
            "address" to "मार्केट यार्ड पत्ता",
            "invoice_prefix" to "बिल इन्व्हॉइस पूर्वप्रत्यय (Prefix)",
            "upi_id" to "यूपीआय आयडी (VPA)",
            "bank_name" to "बँकेचे नाव",
            "bank_acc_name" to "खातेदाराचे नाव",
            "bank_acc_num" to "खाते क्रमांक",
            "bank_ifsc" to "आयएफएससी (IFSC) कोड",
            "printer_settings" to "प्रिंटर सेटअप",
            "theme" to "सिस्टम थीम",
            "language" to "सिस्टम भाषा",
            "save_changes" to "जतन करा आणि पुढे चला",
            "finish_setup" to "सेटअप पूर्ण करा",
            "back" to "मागे",
            "skip" to "वगळा",
            "preset_logo" to "व्यवसाय चिन्ह निवडा",
            "print_auto" to "जतन केल्यावर आपोआप बिल प्रिंट करा",
            "syncing" to "सुपाबेस क्लाउडवर डेटा अपलोड होत आहे...",
            "sync_done" to "सर्व सेटिंग्ज सुरक्षितपणे जतन आणि सिंक केल्या आहेत!",
            "logo_label" to "लोगो अपलोड करा / ब्रँडिंग निवडा"
        ),
        "Telugu" to mapOf(
            "wizard_title" to "మర్చంట్ ఆన్‌బోర్డింగ్",
            "wizard_subtitle" to "5 శీఘ్ర దశల్లో మీ APMC మండి వ్యాపారాన్ని కాన్ఫిగర్ చేయండి",
            "step_1_title" to "సాధారణ సమాచారం",
            "step_2_title" to "చట్టపరమైన వివరాలు",
            "step_3_title" to "చెల్లింపు వివరాలు",
            "step_4_title" to "ప్రాధాన్యతలు",
            "step_5_title" to "సమీక్ష & సమకాలీకరణ",
            "shop_name" to "షాప్ / సంస్థ పేరు",
            "owner_name" to "యజమాని పేరు",
            "gst_number" to "GST నంబర్ (GSTIN)",
            "apmc_license" to "APMC లైసెన్స్ నంబర్",
            "address" to "మార్కెట్ యార్డ్ చిరునామా",
            "invoice_prefix" to "ఇన్‌వాయిస్ ప్రిఫిక్స్",
            "upi_id" to "UPI ఐడి (VPA)",
            "bank_name" to "బ్యాంకు పేరు",
            "bank_acc_name" to "ఖాతాదారుని పేరు",
            "bank_acc_num" to "ఖాతా సంఖ్య",
            "bank_ifsc" to "IFSC కోడ్",
            "printer_settings" to "ప్రింటర్ సెటప్",
            "theme" to "సిస్టమ్ థీమ్",
            "language" to "సిస్టమ్ భాష",
            "save_changes" to "సేవ్ చేసి కొనసాగించండి",
            "finish_setup" to "సెటప్ పూర్తి చేయండి",
            "back" to "వెనుకకు",
            "skip" to "వదిలివేయి",
            "preset_logo" to "వ్యాపార చిహ్నాన్ని ఎంచుకోండి",
            "print_auto" to "సేవ్ చేసినప్పుడు స్వయంచాలకంగా బిల్ ప్రింట్ చేయి",
            "syncing" to "సూపాబేస్ క్లౌడ్‌కు అప్‌లోడ్ అవుతోంది...",
            "sync_done" to "అన్ని సెట్టింగ్‌లు సురక్షితంగా సేవ్ చేయబడ్డాయి!",
            "logo_label" to "లోగో అప్‌లోడ్ చేయండి"
        )
    )

    fun translate(key: String, language: String): String {
        val dict = translations[language] ?: translations["English"]!!
        return dict[key] ?: translations["English"]?.get(key) ?: key
    }
}
